name = "zenitrox-telegram"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
ZENITROX_URL = "https://zenitroxteam.onrender.com"
TIMEZONE = "Asia/Kolkata"
# Set after you add the bot to your team group and run /chatid there:
TEAM_CHAT_ID = "-5418417734"

[[kv_namespaces]]
binding = "LINKS"
id = "cb7de4ec7be54afaa0768f90378048fb"
